# Generated by Django 4.1.5 on 2023-02-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_file', models.FileField(upload_to='files')),
                ('second_file', models.FileField(upload_to='files')),
            ],
        ),
        migrations.AlterField(
            model_name='files',
            name='first_file',
            field=models.FileField(upload_to='files'),
        ),
        migrations.AlterField(
            model_name='files',
            name='second_file',
            field=models.FileField(upload_to='files'),
        ),
    ]
