# Generated by Django 4.1.5 on 2023-08-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_tfiles_alter_files_first_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='thesis_docx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thesis', models.FileField(upload_to='thesis_files')),
            ],
        ),
    ]
