# Generated by Django 4.1.5 on 2023-07-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_pos_sentence_pos_sentences'),
    ]

    operations = [
        migrations.CreateModel(
            name='words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='pos_sentences',
        ),
    ]
